name: jiwa_bakti
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.6
  dio: ^5.2.1+1
  email_validator: ^3.0.0
  flutter_html: ^3.0.0-alpha.5
  flutter_widget_from_html_core: ^0.17.0
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.8.0
  get_it: ^9.1.1
  go_router: ^17.0.0
  html: ^0.15.4
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  sizer: ^3.1.3
  theme_provider: ^0.6.0
  url_launcher: ^6.1.0
  win32: ^5.3.0
  http: ^1.2.2
  share_plus: ^12.0.1


  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  app_links: ^6.4.1
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
